#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2home.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="secondhome")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertimg(img instance);
    partial void Updateimg(img instance);
    partial void Deleteimg(img instance);
    partial void InsertVideo(Video instance);
    partial void UpdateVideo(Video instance);
    partial void DeleteVideo(Video instance);
    partial void InsertMail(Mail instance);
    partial void UpdateMail(Mail instance);
    partial void DeleteMail(Mail instance);
    partial void InsertMotel(Motel instance);
    partial void UpdateMotel(Motel instance);
    partial void DeleteMotel(Motel instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void InsertRoom(Room instance);
    partial void UpdateRoom(Room instance);
    partial void DeleteRoom(Room instance);
    partial void InsertRoomBill(RoomBill instance);
    partial void UpdateRoomBill(RoomBill instance);
    partial void DeleteRoomBill(RoomBill instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
        public DataClasses1DataContext() :
       base(global::System.Configuration.ConfigurationManager.ConnectionStrings["secondhomeConnectionString"].ConnectionString, mappingSource)
        {

        }
        public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<img> imgs
		{
			get
			{
				return this.GetTable<img>();
			}
		}
		
		public System.Data.Linq.Table<Video> Videos
		{
			get
			{
				return this.GetTable<Video>();
			}
		}
		
		public System.Data.Linq.Table<Mail> Mails
		{
			get
			{
				return this.GetTable<Mail>();
			}
		}
		
		public System.Data.Linq.Table<Motel> Motels
		{
			get
			{
				return this.GetTable<Motel>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<Room> Rooms
		{
			get
			{
				return this.GetTable<Room>();
			}
		}
		
		public System.Data.Linq.Table<RoomBill> RoomBills
		{
			get
			{
				return this.GetTable<RoomBill>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.img")]
	public partial class img : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _img_ID;
		
		private System.Nullable<int> _Motel_ID;
		
		private System.Nullable<System.DateTime> _updatedAt;
		
		private System.Nullable<System.DateTime> _createdAt;
		
		private string _Link;
		
		private EntityRef<Motel> _Motel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimg_IDChanging(int value);
    partial void Onimg_IDChanged();
    partial void OnMotel_IDChanging(System.Nullable<int> value);
    partial void OnMotel_IDChanged();
    partial void OnupdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedAtChanged();
    partial void OncreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedAtChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public img()
		{
			this._Motel = default(EntityRef<Motel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int img_ID
		{
			get
			{
				return this._img_ID;
			}
			set
			{
				if ((this._img_ID != value))
				{
					this.Onimg_IDChanging(value);
					this.SendPropertyChanging();
					this._img_ID = value;
					this.SendPropertyChanged("img_ID");
					this.Onimg_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motel_ID", DbType="Int")]
		public System.Nullable<int> Motel_ID
		{
			get
			{
				return this._Motel_ID;
			}
			set
			{
				if ((this._Motel_ID != value))
				{
					if (this._Motel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMotel_IDChanging(value);
					this.SendPropertyChanging();
					this._Motel_ID = value;
					this.SendPropertyChanged("Motel_ID");
					this.OnMotel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this.OnupdatedAtChanging(value);
					this.SendPropertyChanging();
					this._updatedAt = value;
					this.SendPropertyChanged("updatedAt");
					this.OnupdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(255)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_img", Storage="_Motel", ThisKey="Motel_ID", OtherKey="Motel_ID", IsForeignKey=true)]
		public Motel Motel
		{
			get
			{
				return this._Motel.Entity;
			}
			set
			{
				Motel previousValue = this._Motel.Entity;
				if (((previousValue != value) 
							|| (this._Motel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motel.Entity = null;
						previousValue.imgs.Remove(this);
					}
					this._Motel.Entity = value;
					if ((value != null))
					{
						value.imgs.Add(this);
						this._Motel_ID = value.Motel_ID;
					}
					else
					{
						this._Motel_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Motel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Video")]
	public partial class Video : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _video_ID;
		
		private System.Nullable<int> _Motel_ID;
		
		private System.Nullable<System.DateTime> _updatedAt;
		
		private System.Nullable<System.DateTime> _createdAt;
		
		private string _Link;
		
		private EntityRef<Motel> _Motel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvideo_IDChanging(int value);
    partial void Onvideo_IDChanged();
    partial void OnMotel_IDChanging(System.Nullable<int> value);
    partial void OnMotel_IDChanged();
    partial void OnupdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedAtChanged();
    partial void OncreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedAtChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public Video()
		{
			this._Motel = default(EntityRef<Motel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_video_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int video_ID
		{
			get
			{
				return this._video_ID;
			}
			set
			{
				if ((this._video_ID != value))
				{
					this.Onvideo_IDChanging(value);
					this.SendPropertyChanging();
					this._video_ID = value;
					this.SendPropertyChanged("video_ID");
					this.Onvideo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motel_ID", DbType="Int")]
		public System.Nullable<int> Motel_ID
		{
			get
			{
				return this._Motel_ID;
			}
			set
			{
				if ((this._Motel_ID != value))
				{
					if (this._Motel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMotel_IDChanging(value);
					this.SendPropertyChanging();
					this._Motel_ID = value;
					this.SendPropertyChanged("Motel_ID");
					this.OnMotel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this.OnupdatedAtChanging(value);
					this.SendPropertyChanging();
					this._updatedAt = value;
					this.SendPropertyChanged("updatedAt");
					this.OnupdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(255)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_Video", Storage="_Motel", ThisKey="Motel_ID", OtherKey="Motel_ID", IsForeignKey=true)]
		public Motel Motel
		{
			get
			{
				return this._Motel.Entity;
			}
			set
			{
				Motel previousValue = this._Motel.Entity;
				if (((previousValue != value) 
							|| (this._Motel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motel.Entity = null;
						previousValue.Videos.Remove(this);
					}
					this._Motel.Entity = value;
					if ((value != null))
					{
						value.Videos.Add(this);
						this._Motel_ID = value.Motel_ID;
					}
					else
					{
						this._Motel_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Motel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mail")]
	public partial class Mail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mail_ID;
		
		private System.Nullable<int> _Sender;
		
		private System.Nullable<int> _ID_user;
		
		private System.Nullable<int> _Recipient;
		
		private System.DateTime _SendDate;
		
		private string _Content;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMail_IDChanging(int value);
    partial void OnMail_IDChanged();
    partial void OnSenderChanging(System.Nullable<int> value);
    partial void OnSenderChanged();
    partial void OnID_userChanging(System.Nullable<int> value);
    partial void OnID_userChanged();
    partial void OnRecipientChanging(System.Nullable<int> value);
    partial void OnRecipientChanged();
    partial void OnSendDateChanging(System.DateTime value);
    partial void OnSendDateChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    #endregion
		
		public Mail()
		{
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mail_ID
		{
			get
			{
				return this._Mail_ID;
			}
			set
			{
				if ((this._Mail_ID != value))
				{
					this.OnMail_IDChanging(value);
					this.SendPropertyChanging();
					this._Mail_ID = value;
					this.SendPropertyChanged("Mail_ID");
					this.OnMail_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="Int")]
		public System.Nullable<int> Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int")]
		public System.Nullable<int> ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recipient", DbType="Int")]
		public System.Nullable<int> Recipient
		{
			get
			{
				return this._Recipient;
			}
			set
			{
				if ((this._Recipient != value))
				{
					this.OnRecipientChanging(value);
					this.SendPropertyChanging();
					this._Recipient = value;
					this.SendPropertyChanged("Recipient");
					this.OnRecipientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendDate", DbType="DateTime NOT NULL")]
		public System.DateTime SendDate
		{
			get
			{
				return this._SendDate;
			}
			set
			{
				if ((this._SendDate != value))
				{
					this.OnSendDateChanging(value);
					this.SendPropertyChanging();
					this._SendDate = value;
					this.SendPropertyChanged("SendDate");
					this.OnSendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_Mail", Storage="_user", ThisKey="ID_user", OtherKey="ID_user", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.Mails.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.Mails.Add(this);
						this._ID_user = value.ID_user;
					}
					else
					{
						this._ID_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Motel")]
	public partial class Motel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Motel_ID;
		
		private System.Nullable<int> _ID_user;
		
		private string _Name_motel;
		
		private string _location;
		
		private System.Nullable<decimal> _price;
		
		private string _is_available;
		
		private string _Details;
		
		private System.Nullable<int> _rooms;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<decimal> _Debt;
		
		private EntitySet<img> _imgs;
		
		private EntitySet<Video> _Videos;
		
		private EntitySet<Room> _Rooms1;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMotel_IDChanging(int value);
    partial void OnMotel_IDChanged();
    partial void OnID_userChanging(System.Nullable<int> value);
    partial void OnID_userChanged();
    partial void OnName_motelChanging(string value);
    partial void OnName_motelChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void Onis_availableChanging(string value);
    partial void Onis_availableChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnroomsChanging(System.Nullable<int> value);
    partial void OnroomsChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnDebtChanging(System.Nullable<decimal> value);
    partial void OnDebtChanged();
    #endregion
		
		public Motel()
		{
			this._imgs = new EntitySet<img>(new Action<img>(this.attach_imgs), new Action<img>(this.detach_imgs));
			this._Videos = new EntitySet<Video>(new Action<Video>(this.attach_Videos), new Action<Video>(this.detach_Videos));
			this._Rooms1 = new EntitySet<Room>(new Action<Room>(this.attach_Rooms1), new Action<Room>(this.detach_Rooms1));
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motel_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Motel_ID
		{
			get
			{
				return this._Motel_ID;
			}
			set
			{
				if ((this._Motel_ID != value))
				{
					this.OnMotel_IDChanging(value);
					this.SendPropertyChanging();
					this._Motel_ID = value;
					this.SendPropertyChanged("Motel_ID");
					this.OnMotel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int")]
		public System.Nullable<int> ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_motel", DbType="NVarChar(100)")]
		public string Name_motel
		{
			get
			{
				return this._Name_motel;
			}
			set
			{
				if ((this._Name_motel != value))
				{
					this.OnName_motelChanging(value);
					this.SendPropertyChanging();
					this._Name_motel = value;
					this.SendPropertyChanged("Name_motel");
					this.OnName_motelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(255)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_available", DbType="NVarChar(50)")]
		public string is_available
		{
			get
			{
				return this._is_available;
			}
			set
			{
				if ((this._is_available != value))
				{
					this.Onis_availableChanging(value);
					this.SendPropertyChanging();
					this._is_available = value;
					this.SendPropertyChanged("is_available");
					this.Onis_availableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="NVarChar(MAX)")]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rooms", DbType="Int")]
		public System.Nullable<int> rooms
		{
			get
			{
				return this._rooms;
			}
			set
			{
				if ((this._rooms != value))
				{
					this.OnroomsChanging(value);
					this.SendPropertyChanging();
					this._rooms = value;
					this.SendPropertyChanged("rooms");
					this.OnroomsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debt", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Debt
		{
			get
			{
				return this._Debt;
			}
			set
			{
				if ((this._Debt != value))
				{
					this.OnDebtChanging(value);
					this.SendPropertyChanging();
					this._Debt = value;
					this.SendPropertyChanged("Debt");
					this.OnDebtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_img", Storage="_imgs", ThisKey="Motel_ID", OtherKey="Motel_ID")]
		public EntitySet<img> imgs
		{
			get
			{
				return this._imgs;
			}
			set
			{
				this._imgs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_Video", Storage="_Videos", ThisKey="Motel_ID", OtherKey="Motel_ID")]
		public EntitySet<Video> Videos
		{
			get
			{
				return this._Videos;
			}
			set
			{
				this._Videos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_Room", Storage="_Rooms1", ThisKey="Motel_ID", OtherKey="Motel_ID")]
		public EntitySet<Room> Rooms1
		{
			get
			{
				return this._Rooms1;
			}
			set
			{
				this._Rooms1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_Motel", Storage="_user", ThisKey="ID_user", OtherKey="ID_user", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.Motels.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.Motels.Add(this);
						this._ID_user = value.ID_user;
					}
					else
					{
						this._ID_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_imgs(img entity)
		{
			this.SendPropertyChanging();
			entity.Motel = this;
		}
		
		private void detach_imgs(img entity)
		{
			this.SendPropertyChanging();
			entity.Motel = null;
		}
		
		private void attach_Videos(Video entity)
		{
			this.SendPropertyChanging();
			entity.Motel = this;
		}
		
		private void detach_Videos(Video entity)
		{
			this.SendPropertyChanging();
			entity.Motel = null;
		}
		
		private void attach_Rooms1(Room entity)
		{
			this.SendPropertyChanging();
			entity.Motel = this;
		}
		
		private void detach_Rooms1(Room entity)
		{
			this.SendPropertyChanging();
			entity.Motel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_user;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private System.Nullable<int> _MotelID;
		
		private string _PhoneNumber;
		
		private string _Email;
		
		private string _userrole;
		
		private string _gender;
		
		private System.Nullable<int> _blance;
		
		private EntitySet<Mail> _Mails;
		
		private EntitySet<Motel> _Motels;
		
		private EntitySet<Room> _Rooms;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_userChanging(int value);
    partial void OnID_userChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnMotelIDChanging(System.Nullable<int> value);
    partial void OnMotelIDChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnuserroleChanging(string value);
    partial void OnuserroleChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnblanceChanging(System.Nullable<int> value);
    partial void OnblanceChanged();
    #endregion
		
		public user()
		{
			this._Mails = new EntitySet<Mail>(new Action<Mail>(this.attach_Mails), new Action<Mail>(this.detach_Mails));
			this._Motels = new EntitySet<Motel>(new Action<Motel>(this.attach_Motels), new Action<Motel>(this.detach_Motels));
			this._Rooms = new EntitySet<Room>(new Action<Room>(this.attach_Rooms), new Action<Room>(this.detach_Rooms));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(100)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotelID", DbType="Int")]
		public System.Nullable<int> MotelID
		{
			get
			{
				return this._MotelID;
			}
			set
			{
				if ((this._MotelID != value))
				{
					this.OnMotelIDChanging(value);
					this.SendPropertyChanging();
					this._MotelID = value;
					this.SendPropertyChanged("MotelID");
					this.OnMotelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(15)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userrole", DbType="NVarChar(50)")]
		public string userrole
		{
			get
			{
				return this._userrole;
			}
			set
			{
				if ((this._userrole != value))
				{
					this.OnuserroleChanging(value);
					this.SendPropertyChanging();
					this._userrole = value;
					this.SendPropertyChanged("userrole");
					this.OnuserroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blance", DbType="Int")]
		public System.Nullable<int> blance
		{
			get
			{
				return this._blance;
			}
			set
			{
				if ((this._blance != value))
				{
					this.OnblanceChanging(value);
					this.SendPropertyChanging();
					this._blance = value;
					this.SendPropertyChanged("blance");
					this.OnblanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_Mail", Storage="_Mails", ThisKey="ID_user", OtherKey="ID_user")]
		public EntitySet<Mail> Mails
		{
			get
			{
				return this._Mails;
			}
			set
			{
				this._Mails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_Motel", Storage="_Motels", ThisKey="ID_user", OtherKey="ID_user")]
		public EntitySet<Motel> Motels
		{
			get
			{
				return this._Motels;
			}
			set
			{
				this._Motels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_Room", Storage="_Rooms", ThisKey="ID_user", OtherKey="ID_user")]
		public EntitySet<Room> Rooms
		{
			get
			{
				return this._Rooms;
			}
			set
			{
				this._Rooms.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Mails(Mail entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_Mails(Mail entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_Motels(Motel entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_Motels(Motel entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_Rooms(Room entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_Rooms(Room entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rooms")]
	public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _room_ID;
		
		private System.Nullable<int> _Motel_ID;
		
		private System.Nullable<int> _ID_user;
		
		private System.Nullable<System.DateTime> _Date_of_Issue;
		
		private System.Nullable<decimal> _Electricity_Meter;
		
		private System.Nullable<decimal> _Water_Meter;
		
		private System.Nullable<decimal> _Electricity_Unit_Price;
		
		private System.Nullable<decimal> _Water_Unit_Price;
		
		private System.Nullable<decimal> _Previous_Water_Meter;
		
		private System.Nullable<decimal> _Previous_Electricity_Usage;
		
		private System.Nullable<decimal> _Electricity_Bill;
		
		private System.Nullable<decimal> _Water_Bill;
		
		private string _Room_Status;
		
		private System.Nullable<decimal> _Additional_Charges;
		
		private System.Nullable<decimal> _Room_Rent;
		
		private EntitySet<RoomBill> _RoomBills;
		
		private EntityRef<user> _user;
		
		private EntityRef<Motel> _Motel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onroom_IDChanging(int value);
    partial void Onroom_IDChanged();
    partial void OnMotel_IDChanging(System.Nullable<int> value);
    partial void OnMotel_IDChanged();
    partial void OnID_userChanging(System.Nullable<int> value);
    partial void OnID_userChanged();
    partial void OnDate_of_IssueChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_IssueChanged();
    partial void OnElectricity_MeterChanging(System.Nullable<decimal> value);
    partial void OnElectricity_MeterChanged();
    partial void OnWater_MeterChanging(System.Nullable<decimal> value);
    partial void OnWater_MeterChanged();
    partial void OnElectricity_Unit_PriceChanging(System.Nullable<decimal> value);
    partial void OnElectricity_Unit_PriceChanged();
    partial void OnWater_Unit_PriceChanging(System.Nullable<decimal> value);
    partial void OnWater_Unit_PriceChanged();
    partial void OnPrevious_Water_MeterChanging(System.Nullable<decimal> value);
    partial void OnPrevious_Water_MeterChanged();
    partial void OnPrevious_Electricity_UsageChanging(System.Nullable<decimal> value);
    partial void OnPrevious_Electricity_UsageChanged();
    partial void OnElectricity_BillChanging(System.Nullable<decimal> value);
    partial void OnElectricity_BillChanged();
    partial void OnWater_BillChanging(System.Nullable<decimal> value);
    partial void OnWater_BillChanged();
    partial void OnRoom_StatusChanging(string value);
    partial void OnRoom_StatusChanged();
    partial void OnAdditional_ChargesChanging(System.Nullable<decimal> value);
    partial void OnAdditional_ChargesChanged();
    partial void OnRoom_RentChanging(System.Nullable<decimal> value);
    partial void OnRoom_RentChanged();
    #endregion
		
		public Room()
		{
			this._RoomBills = new EntitySet<RoomBill>(new Action<RoomBill>(this.attach_RoomBills), new Action<RoomBill>(this.detach_RoomBills));
			this._user = default(EntityRef<user>);
			this._Motel = default(EntityRef<Motel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int room_ID
		{
			get
			{
				return this._room_ID;
			}
			set
			{
				if ((this._room_ID != value))
				{
					this.Onroom_IDChanging(value);
					this.SendPropertyChanging();
					this._room_ID = value;
					this.SendPropertyChanged("room_ID");
					this.Onroom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motel_ID", DbType="Int")]
		public System.Nullable<int> Motel_ID
		{
			get
			{
				return this._Motel_ID;
			}
			set
			{
				if ((this._Motel_ID != value))
				{
					if (this._Motel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMotel_IDChanging(value);
					this.SendPropertyChanging();
					this._Motel_ID = value;
					this.SendPropertyChanged("Motel_ID");
					this.OnMotel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int")]
		public System.Nullable<int> ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_Issue", DbType="Date")]
		public System.Nullable<System.DateTime> Date_of_Issue
		{
			get
			{
				return this._Date_of_Issue;
			}
			set
			{
				if ((this._Date_of_Issue != value))
				{
					this.OnDate_of_IssueChanging(value);
					this.SendPropertyChanging();
					this._Date_of_Issue = value;
					this.SendPropertyChanged("Date_of_Issue");
					this.OnDate_of_IssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Meter", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Electricity_Meter
		{
			get
			{
				return this._Electricity_Meter;
			}
			set
			{
				if ((this._Electricity_Meter != value))
				{
					this.OnElectricity_MeterChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Meter = value;
					this.SendPropertyChanged("Electricity_Meter");
					this.OnElectricity_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Meter", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Water_Meter
		{
			get
			{
				return this._Water_Meter;
			}
			set
			{
				if ((this._Water_Meter != value))
				{
					this.OnWater_MeterChanging(value);
					this.SendPropertyChanging();
					this._Water_Meter = value;
					this.SendPropertyChanged("Water_Meter");
					this.OnWater_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Unit_Price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Electricity_Unit_Price
		{
			get
			{
				return this._Electricity_Unit_Price;
			}
			set
			{
				if ((this._Electricity_Unit_Price != value))
				{
					this.OnElectricity_Unit_PriceChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Unit_Price = value;
					this.SendPropertyChanged("Electricity_Unit_Price");
					this.OnElectricity_Unit_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Unit_Price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Water_Unit_Price
		{
			get
			{
				return this._Water_Unit_Price;
			}
			set
			{
				if ((this._Water_Unit_Price != value))
				{
					this.OnWater_Unit_PriceChanging(value);
					this.SendPropertyChanging();
					this._Water_Unit_Price = value;
					this.SendPropertyChanged("Water_Unit_Price");
					this.OnWater_Unit_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Previous_Water_Meter", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Previous_Water_Meter
		{
			get
			{
				return this._Previous_Water_Meter;
			}
			set
			{
				if ((this._Previous_Water_Meter != value))
				{
					this.OnPrevious_Water_MeterChanging(value);
					this.SendPropertyChanging();
					this._Previous_Water_Meter = value;
					this.SendPropertyChanged("Previous_Water_Meter");
					this.OnPrevious_Water_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Previous_Electricity_Usage", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Previous_Electricity_Usage
		{
			get
			{
				return this._Previous_Electricity_Usage;
			}
			set
			{
				if ((this._Previous_Electricity_Usage != value))
				{
					this.OnPrevious_Electricity_UsageChanging(value);
					this.SendPropertyChanging();
					this._Previous_Electricity_Usage = value;
					this.SendPropertyChanged("Previous_Electricity_Usage");
					this.OnPrevious_Electricity_UsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Bill", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Electricity_Bill
		{
			get
			{
				return this._Electricity_Bill;
			}
			set
			{
				if ((this._Electricity_Bill != value))
				{
					this.OnElectricity_BillChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Bill = value;
					this.SendPropertyChanged("Electricity_Bill");
					this.OnElectricity_BillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Bill", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Water_Bill
		{
			get
			{
				return this._Water_Bill;
			}
			set
			{
				if ((this._Water_Bill != value))
				{
					this.OnWater_BillChanging(value);
					this.SendPropertyChanging();
					this._Water_Bill = value;
					this.SendPropertyChanged("Water_Bill");
					this.OnWater_BillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Status", DbType="NVarChar(50)")]
		public string Room_Status
		{
			get
			{
				return this._Room_Status;
			}
			set
			{
				if ((this._Room_Status != value))
				{
					this.OnRoom_StatusChanging(value);
					this.SendPropertyChanging();
					this._Room_Status = value;
					this.SendPropertyChanged("Room_Status");
					this.OnRoom_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Additional_Charges", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Additional_Charges
		{
			get
			{
				return this._Additional_Charges;
			}
			set
			{
				if ((this._Additional_Charges != value))
				{
					this.OnAdditional_ChargesChanging(value);
					this.SendPropertyChanging();
					this._Additional_Charges = value;
					this.SendPropertyChanged("Additional_Charges");
					this.OnAdditional_ChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Rent", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Room_Rent
		{
			get
			{
				return this._Room_Rent;
			}
			set
			{
				if ((this._Room_Rent != value))
				{
					this.OnRoom_RentChanging(value);
					this.SendPropertyChanging();
					this._Room_Rent = value;
					this.SendPropertyChanged("Room_Rent");
					this.OnRoom_RentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_RoomBill", Storage="_RoomBills", ThisKey="room_ID", OtherKey="Room_ID")]
		public EntitySet<RoomBill> RoomBills
		{
			get
			{
				return this._RoomBills;
			}
			set
			{
				this._RoomBills.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_Room", Storage="_user", ThisKey="ID_user", OtherKey="ID_user", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.Rooms.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.Rooms.Add(this);
						this._ID_user = value.ID_user;
					}
					else
					{
						this._ID_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_Room", Storage="_Motel", ThisKey="Motel_ID", OtherKey="Motel_ID", IsForeignKey=true)]
		public Motel Motel
		{
			get
			{
				return this._Motel.Entity;
			}
			set
			{
				Motel previousValue = this._Motel.Entity;
				if (((previousValue != value) 
							|| (this._Motel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motel.Entity = null;
						previousValue.Rooms1.Remove(this);
					}
					this._Motel.Entity = value;
					if ((value != null))
					{
						value.Rooms1.Add(this);
						this._Motel_ID = value.Motel_ID;
					}
					else
					{
						this._Motel_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Motel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RoomBills(RoomBill entity)
		{
			this.SendPropertyChanging();
			entity.Room = this;
		}
		
		private void detach_RoomBills(RoomBill entity)
		{
			this.SendPropertyChanging();
			entity.Room = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoomBills")]
	public partial class RoomBill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Bill_ID;
		
		private int _Room_ID;
		
		private decimal _Previous_Electricity_Usage;
		
		private System.Nullable<decimal> _Electricity_Meter;
		
		private System.Nullable<decimal> _Previous_Water_Meter;
		
		private System.Nullable<decimal> _Water_Meter;
		
		private System.Nullable<decimal> _Additional_Charges;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<decimal> _Electricity_Bill;
		
		private System.Nullable<decimal> _Water_Bill;
		
		private System.Nullable<decimal> _Total_Amount_Due;
		
		private string _Room_Status;
		
		private System.Nullable<System.DateTime> _Date_of_Issue;
		
		private EntityRef<Room> _Room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBill_IDChanging(int value);
    partial void OnBill_IDChanged();
    partial void OnRoom_IDChanging(int value);
    partial void OnRoom_IDChanged();
    partial void OnPrevious_Electricity_UsageChanging(decimal value);
    partial void OnPrevious_Electricity_UsageChanged();
    partial void OnElectricity_MeterChanging(System.Nullable<decimal> value);
    partial void OnElectricity_MeterChanged();
    partial void OnPrevious_Water_MeterChanging(System.Nullable<decimal> value);
    partial void OnPrevious_Water_MeterChanged();
    partial void OnWater_MeterChanging(System.Nullable<decimal> value);
    partial void OnWater_MeterChanged();
    partial void OnAdditional_ChargesChanging(System.Nullable<decimal> value);
    partial void OnAdditional_ChargesChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnElectricity_BillChanging(System.Nullable<decimal> value);
    partial void OnElectricity_BillChanged();
    partial void OnWater_BillChanging(System.Nullable<decimal> value);
    partial void OnWater_BillChanged();
    partial void OnTotal_Amount_DueChanging(System.Nullable<decimal> value);
    partial void OnTotal_Amount_DueChanged();
    partial void OnRoom_StatusChanging(string value);
    partial void OnRoom_StatusChanged();
    partial void OnDate_of_IssueChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_IssueChanged();
    #endregion
		
		public RoomBill()
		{
			this._Room = default(EntityRef<Room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Bill_ID
		{
			get
			{
				return this._Bill_ID;
			}
			set
			{
				if ((this._Bill_ID != value))
				{
					this.OnBill_IDChanging(value);
					this.SendPropertyChanging();
					this._Bill_ID = value;
					this.SendPropertyChanged("Bill_ID");
					this.OnBill_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_ID", DbType="Int NOT NULL")]
		public int Room_ID
		{
			get
			{
				return this._Room_ID;
			}
			set
			{
				if ((this._Room_ID != value))
				{
					if (this._Room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoom_IDChanging(value);
					this.SendPropertyChanging();
					this._Room_ID = value;
					this.SendPropertyChanged("Room_ID");
					this.OnRoom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Previous_Electricity_Usage", DbType="Decimal(10,2) NOT NULL")]
		public decimal Previous_Electricity_Usage
		{
			get
			{
				return this._Previous_Electricity_Usage;
			}
			set
			{
				if ((this._Previous_Electricity_Usage != value))
				{
					this.OnPrevious_Electricity_UsageChanging(value);
					this.SendPropertyChanging();
					this._Previous_Electricity_Usage = value;
					this.SendPropertyChanged("Previous_Electricity_Usage");
					this.OnPrevious_Electricity_UsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Meter", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Electricity_Meter
		{
			get
			{
				return this._Electricity_Meter;
			}
			set
			{
				if ((this._Electricity_Meter != value))
				{
					this.OnElectricity_MeterChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Meter = value;
					this.SendPropertyChanged("Electricity_Meter");
					this.OnElectricity_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Previous_Water_Meter", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Previous_Water_Meter
		{
			get
			{
				return this._Previous_Water_Meter;
			}
			set
			{
				if ((this._Previous_Water_Meter != value))
				{
					this.OnPrevious_Water_MeterChanging(value);
					this.SendPropertyChanging();
					this._Previous_Water_Meter = value;
					this.SendPropertyChanged("Previous_Water_Meter");
					this.OnPrevious_Water_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Meter", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Water_Meter
		{
			get
			{
				return this._Water_Meter;
			}
			set
			{
				if ((this._Water_Meter != value))
				{
					this.OnWater_MeterChanging(value);
					this.SendPropertyChanging();
					this._Water_Meter = value;
					this.SendPropertyChanged("Water_Meter");
					this.OnWater_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Additional_Charges", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Additional_Charges
		{
			get
			{
				return this._Additional_Charges;
			}
			set
			{
				if ((this._Additional_Charges != value))
				{
					this.OnAdditional_ChargesChanging(value);
					this.SendPropertyChanging();
					this._Additional_Charges = value;
					this.SendPropertyChanged("Additional_Charges");
					this.OnAdditional_ChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Bill", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Electricity_Bill
		{
			get
			{
				return this._Electricity_Bill;
			}
			set
			{
				if ((this._Electricity_Bill != value))
				{
					this.OnElectricity_BillChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Bill = value;
					this.SendPropertyChanged("Electricity_Bill");
					this.OnElectricity_BillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Bill", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Water_Bill
		{
			get
			{
				return this._Water_Bill;
			}
			set
			{
				if ((this._Water_Bill != value))
				{
					this.OnWater_BillChanging(value);
					this.SendPropertyChanging();
					this._Water_Bill = value;
					this.SendPropertyChanged("Water_Bill");
					this.OnWater_BillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Amount_Due", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Total_Amount_Due
		{
			get
			{
				return this._Total_Amount_Due;
			}
			set
			{
				if ((this._Total_Amount_Due != value))
				{
					this.OnTotal_Amount_DueChanging(value);
					this.SendPropertyChanging();
					this._Total_Amount_Due = value;
					this.SendPropertyChanged("Total_Amount_Due");
					this.OnTotal_Amount_DueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Status", DbType="VarChar(50)")]
		public string Room_Status
		{
			get
			{
				return this._Room_Status;
			}
			set
			{
				if ((this._Room_Status != value))
				{
					this.OnRoom_StatusChanging(value);
					this.SendPropertyChanging();
					this._Room_Status = value;
					this.SendPropertyChanged("Room_Status");
					this.OnRoom_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_Issue", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_of_Issue
		{
			get
			{
				return this._Date_of_Issue;
			}
			set
			{
				if ((this._Date_of_Issue != value))
				{
					this.OnDate_of_IssueChanging(value);
					this.SendPropertyChanging();
					this._Date_of_Issue = value;
					this.SendPropertyChanged("Date_of_Issue");
					this.OnDate_of_IssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_RoomBill", Storage="_Room", ThisKey="Room_ID", OtherKey="room_ID", IsForeignKey=true)]
		public Room Room
		{
			get
			{
				return this._Room.Entity;
			}
			set
			{
				Room previousValue = this._Room.Entity;
				if (((previousValue != value) 
							|| (this._Room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Room.Entity = null;
						previousValue.RoomBills.Remove(this);
					}
					this._Room.Entity = value;
					if ((value != null))
					{
						value.RoomBills.Add(this);
						this._Room_ID = value.room_ID;
					}
					else
					{
						this._Room_ID = default(int);
					}
					this.SendPropertyChanged("Room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
