#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2home.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="secondhome")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertimg(img instance);
    partial void Updateimg(img instance);
    partial void Deleteimg(img instance);
    partial void InsertMotel(Motel instance);
    partial void UpdateMotel(Motel instance);
    partial void DeleteMotel(Motel instance);
    partial void InsertRoom_Invoice(Room_Invoice instance);
    partial void UpdateRoom_Invoice(Room_Invoice instance);
    partial void DeleteRoom_Invoice(Room_Invoice instance);
    partial void Insertroom(room instance);
    partial void Updateroom(room instance);
    partial void Deleteroom(room instance);
    partial void InsertUserProfile(UserProfile instance);
    partial void UpdateUserProfile(UserProfile instance);
    partial void DeleteUserProfile(UserProfile instance);
    partial void InsertVideo(Video instance);
    partial void UpdateVideo(Video instance);
    partial void DeleteVideo(Video instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
        public DataClasses1DataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["secondhomeConnectionString1"].ConnectionString, mappingSource)
        {

        }
        public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<img> imgs
		{
			get
			{
				return this.GetTable<img>();
			}
		}
		
		public System.Data.Linq.Table<Motel> Motels
		{
			get
			{
				return this.GetTable<Motel>();
			}
		}
		
		public System.Data.Linq.Table<Room_Invoice> Room_Invoices
		{
			get
			{
				return this.GetTable<Room_Invoice>();
			}
		}
		
		public System.Data.Linq.Table<room> rooms
		{
			get
			{
				return this.GetTable<room>();
			}
		}
		
		public System.Data.Linq.Table<UserProfile> UserProfiles
		{
			get
			{
				return this.GetTable<UserProfile>();
			}
		}
		
		public System.Data.Linq.Table<Video> Videos
		{
			get
			{
				return this.GetTable<Video>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.img")]
	public partial class img : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _img_ID;
		
		private System.Nullable<int> _ID_user;
		
		private System.Nullable<System.DateTime> _updatedAt;
		
		private System.Nullable<System.DateTime> _createdAt;
		
		private string _Link;
		
		private EntityRef<UserProfile> _UserProfile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimg_IDChanging(int value);
    partial void Onimg_IDChanged();
    partial void OnID_userChanging(System.Nullable<int> value);
    partial void OnID_userChanged();
    partial void OnupdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedAtChanged();
    partial void OncreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedAtChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public img()
		{
			this._UserProfile = default(EntityRef<UserProfile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int img_ID
		{
			get
			{
				return this._img_ID;
			}
			set
			{
				if ((this._img_ID != value))
				{
					this.Onimg_IDChanging(value);
					this.SendPropertyChanging();
					this._img_ID = value;
					this.SendPropertyChanged("img_ID");
					this.Onimg_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int")]
		public System.Nullable<int> ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					if (this._UserProfile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedAt", DbType="Date")]
		public System.Nullable<System.DateTime> updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this.OnupdatedAtChanging(value);
					this.SendPropertyChanging();
					this._updatedAt = value;
					this.SendPropertyChanged("updatedAt");
					this.OnupdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="Date")]
		public System.Nullable<System.DateTime> createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(255)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserProfile_img", Storage="_UserProfile", ThisKey="ID_user", OtherKey="ID_user", IsForeignKey=true)]
		public UserProfile UserProfile
		{
			get
			{
				return this._UserProfile.Entity;
			}
			set
			{
				UserProfile previousValue = this._UserProfile.Entity;
				if (((previousValue != value) 
							|| (this._UserProfile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserProfile.Entity = null;
						previousValue.imgs.Remove(this);
					}
					this._UserProfile.Entity = value;
					if ((value != null))
					{
						value.imgs.Add(this);
						this._ID_user = value.ID_user;
					}
					else
					{
						this._ID_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("UserProfile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Motel")]
	public partial class Motel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Motel_ID;
		
		private System.Nullable<int> _ID_user;
		
		private string _Name_motel;
		
		private string _Postal_Code;
		
		private string _location;
		
		private System.Nullable<decimal> _price;
		
		private System.Nullable<bool> _is_available;
		
		private EntitySet<room> _rooms;
		
		private EntityRef<UserProfile> _UserProfile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMotel_IDChanging(int value);
    partial void OnMotel_IDChanged();
    partial void OnID_userChanging(System.Nullable<int> value);
    partial void OnID_userChanged();
    partial void OnName_motelChanging(string value);
    partial void OnName_motelChanged();
    partial void OnPostal_CodeChanging(string value);
    partial void OnPostal_CodeChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void Onis_availableChanging(System.Nullable<bool> value);
    partial void Onis_availableChanged();
    #endregion
		
		public Motel()
		{
			this._rooms = new EntitySet<room>(new Action<room>(this.attach_rooms), new Action<room>(this.detach_rooms));
			this._UserProfile = default(EntityRef<UserProfile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motel_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Motel_ID
		{
			get
			{
				return this._Motel_ID;
			}
			set
			{
				if ((this._Motel_ID != value))
				{
					this.OnMotel_IDChanging(value);
					this.SendPropertyChanging();
					this._Motel_ID = value;
					this.SendPropertyChanged("Motel_ID");
					this.OnMotel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int")]
		public System.Nullable<int> ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					if (this._UserProfile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_motel", DbType="VarChar(255)")]
		public string Name_motel
		{
			get
			{
				return this._Name_motel;
			}
			set
			{
				if ((this._Name_motel != value))
				{
					this.OnName_motelChanging(value);
					this.SendPropertyChanging();
					this._Name_motel = value;
					this.SendPropertyChanged("Name_motel");
					this.OnName_motelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal_Code", DbType="VarChar(255)")]
		public string Postal_Code
		{
			get
			{
				return this._Postal_Code;
			}
			set
			{
				if ((this._Postal_Code != value))
				{
					this.OnPostal_CodeChanging(value);
					this.SendPropertyChanging();
					this._Postal_Code = value;
					this.SendPropertyChanged("Postal_Code");
					this.OnPostal_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(255)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_available", DbType="Bit")]
		public System.Nullable<bool> is_available
		{
			get
			{
				return this._is_available;
			}
			set
			{
				if ((this._is_available != value))
				{
					this.Onis_availableChanging(value);
					this.SendPropertyChanging();
					this._is_available = value;
					this.SendPropertyChanged("is_available");
					this.Onis_availableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_room", Storage="_rooms", ThisKey="Motel_ID", OtherKey="Motel_ID")]
		public EntitySet<room> rooms
		{
			get
			{
				return this._rooms;
			}
			set
			{
				this._rooms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserProfile_Motel", Storage="_UserProfile", ThisKey="ID_user", OtherKey="ID_user", IsForeignKey=true)]
		public UserProfile UserProfile
		{
			get
			{
				return this._UserProfile.Entity;
			}
			set
			{
				UserProfile previousValue = this._UserProfile.Entity;
				if (((previousValue != value) 
							|| (this._UserProfile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserProfile.Entity = null;
						previousValue.Motels.Remove(this);
					}
					this._UserProfile.Entity = value;
					if ((value != null))
					{
						value.Motels.Add(this);
						this._ID_user = value.ID_user;
					}
					else
					{
						this._ID_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("UserProfile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_rooms(room entity)
		{
			this.SendPropertyChanging();
			entity.Motel = this;
		}
		
		private void detach_rooms(room entity)
		{
			this.SendPropertyChanging();
			entity.Motel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Room_Invoice")]
	public partial class Room_Invoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Motel_ID;
		
		private int _room_ID;
		
		private System.Nullable<System.DateTime> _Date_of_issue;
		
		private System.Nullable<int> _Electricity_Meter;
		
		private System.Nullable<int> _Water_Meter;
		
		private System.Nullable<decimal> _Electricity_Usage;
		
		private System.Nullable<decimal> _Water_Usage;
		
		private System.Nullable<decimal> _Electricity_Bill;
		
		private System.Nullable<decimal> _Water_Bill;
		
		private string _Room_Status;
		
		private System.Nullable<decimal> _Room_Rent;
		
		private System.Nullable<decimal> _Additional_Charges;
		
		private System.Nullable<decimal> _Total_Amount_Due;
		
		private EntityRef<room> _room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMotel_IDChanging(int value);
    partial void OnMotel_IDChanged();
    partial void Onroom_IDChanging(int value);
    partial void Onroom_IDChanged();
    partial void OnDate_of_issueChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_of_issueChanged();
    partial void OnElectricity_MeterChanging(System.Nullable<int> value);
    partial void OnElectricity_MeterChanged();
    partial void OnWater_MeterChanging(System.Nullable<int> value);
    partial void OnWater_MeterChanged();
    partial void OnElectricity_UsageChanging(System.Nullable<decimal> value);
    partial void OnElectricity_UsageChanged();
    partial void OnWater_UsageChanging(System.Nullable<decimal> value);
    partial void OnWater_UsageChanged();
    partial void OnElectricity_BillChanging(System.Nullable<decimal> value);
    partial void OnElectricity_BillChanged();
    partial void OnWater_BillChanging(System.Nullable<decimal> value);
    partial void OnWater_BillChanged();
    partial void OnRoom_StatusChanging(string value);
    partial void OnRoom_StatusChanged();
    partial void OnRoom_RentChanging(System.Nullable<decimal> value);
    partial void OnRoom_RentChanged();
    partial void OnAdditional_ChargesChanging(System.Nullable<decimal> value);
    partial void OnAdditional_ChargesChanged();
    partial void OnTotal_Amount_DueChanging(System.Nullable<decimal> value);
    partial void OnTotal_Amount_DueChanged();
    #endregion
		
		public Room_Invoice()
		{
			this._room = default(EntityRef<room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motel_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Motel_ID
		{
			get
			{
				return this._Motel_ID;
			}
			set
			{
				if ((this._Motel_ID != value))
				{
					if (this._room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMotel_IDChanging(value);
					this.SendPropertyChanging();
					this._Motel_ID = value;
					this.SendPropertyChanged("Motel_ID");
					this.OnMotel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int room_ID
		{
			get
			{
				return this._room_ID;
			}
			set
			{
				if ((this._room_ID != value))
				{
					if (this._room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onroom_IDChanging(value);
					this.SendPropertyChanging();
					this._room_ID = value;
					this.SendPropertyChanged("room_ID");
					this.Onroom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_issue", DbType="Date")]
		public System.Nullable<System.DateTime> Date_of_issue
		{
			get
			{
				return this._Date_of_issue;
			}
			set
			{
				if ((this._Date_of_issue != value))
				{
					this.OnDate_of_issueChanging(value);
					this.SendPropertyChanging();
					this._Date_of_issue = value;
					this.SendPropertyChanged("Date_of_issue");
					this.OnDate_of_issueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Meter", DbType="Int")]
		public System.Nullable<int> Electricity_Meter
		{
			get
			{
				return this._Electricity_Meter;
			}
			set
			{
				if ((this._Electricity_Meter != value))
				{
					this.OnElectricity_MeterChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Meter = value;
					this.SendPropertyChanged("Electricity_Meter");
					this.OnElectricity_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Meter", DbType="Int")]
		public System.Nullable<int> Water_Meter
		{
			get
			{
				return this._Water_Meter;
			}
			set
			{
				if ((this._Water_Meter != value))
				{
					this.OnWater_MeterChanging(value);
					this.SendPropertyChanging();
					this._Water_Meter = value;
					this.SendPropertyChanged("Water_Meter");
					this.OnWater_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Usage", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Electricity_Usage
		{
			get
			{
				return this._Electricity_Usage;
			}
			set
			{
				if ((this._Electricity_Usage != value))
				{
					this.OnElectricity_UsageChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Usage = value;
					this.SendPropertyChanged("Electricity_Usage");
					this.OnElectricity_UsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Usage", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Water_Usage
		{
			get
			{
				return this._Water_Usage;
			}
			set
			{
				if ((this._Water_Usage != value))
				{
					this.OnWater_UsageChanging(value);
					this.SendPropertyChanging();
					this._Water_Usage = value;
					this.SendPropertyChanged("Water_Usage");
					this.OnWater_UsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Bill", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Electricity_Bill
		{
			get
			{
				return this._Electricity_Bill;
			}
			set
			{
				if ((this._Electricity_Bill != value))
				{
					this.OnElectricity_BillChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Bill = value;
					this.SendPropertyChanged("Electricity_Bill");
					this.OnElectricity_BillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Bill", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Water_Bill
		{
			get
			{
				return this._Water_Bill;
			}
			set
			{
				if ((this._Water_Bill != value))
				{
					this.OnWater_BillChanging(value);
					this.SendPropertyChanging();
					this._Water_Bill = value;
					this.SendPropertyChanged("Water_Bill");
					this.OnWater_BillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Status", DbType="VarChar(255)")]
		public string Room_Status
		{
			get
			{
				return this._Room_Status;
			}
			set
			{
				if ((this._Room_Status != value))
				{
					this.OnRoom_StatusChanging(value);
					this.SendPropertyChanging();
					this._Room_Status = value;
					this.SendPropertyChanged("Room_Status");
					this.OnRoom_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Rent", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Room_Rent
		{
			get
			{
				return this._Room_Rent;
			}
			set
			{
				if ((this._Room_Rent != value))
				{
					this.OnRoom_RentChanging(value);
					this.SendPropertyChanging();
					this._Room_Rent = value;
					this.SendPropertyChanged("Room_Rent");
					this.OnRoom_RentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Additional_Charges", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Additional_Charges
		{
			get
			{
				return this._Additional_Charges;
			}
			set
			{
				if ((this._Additional_Charges != value))
				{
					this.OnAdditional_ChargesChanging(value);
					this.SendPropertyChanging();
					this._Additional_Charges = value;
					this.SendPropertyChanged("Additional_Charges");
					this.OnAdditional_ChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Amount_Due", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Total_Amount_Due
		{
			get
			{
				return this._Total_Amount_Due;
			}
			set
			{
				if ((this._Total_Amount_Due != value))
				{
					this.OnTotal_Amount_DueChanging(value);
					this.SendPropertyChanging();
					this._Total_Amount_Due = value;
					this.SendPropertyChanged("Total_Amount_Due");
					this.OnTotal_Amount_DueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="room_Room_Invoice", Storage="_room", ThisKey="Motel_ID,room_ID", OtherKey="Motel_ID,room_ID", IsForeignKey=true)]
		public room room
		{
			get
			{
				return this._room.Entity;
			}
			set
			{
				room previousValue = this._room.Entity;
				if (((previousValue != value) 
							|| (this._room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._room.Entity = null;
						previousValue.Room_Invoice = null;
					}
					this._room.Entity = value;
					if ((value != null))
					{
						value.Room_Invoice = this;
						this._Motel_ID = value.Motel_ID;
						this._room_ID = value.room_ID;
					}
					else
					{
						this._Motel_ID = default(int);
						this._room_ID = default(int);
					}
					this.SendPropertyChanged("room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rooms")]
	public partial class room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Motel_ID;
		
		private int _room_ID;
		
		private System.Nullable<int> _Electricity_Meter;
		
		private System.Nullable<int> _Water_Meter;
		
		private System.Nullable<decimal> _Electricity_Usage;
		
		private System.Nullable<decimal> _Water_Usage;
		
		private string _Room_Status;
		
		private System.Nullable<decimal> _Room_Rent;
		
		private EntityRef<Room_Invoice> _Room_Invoice;
		
		private EntityRef<Motel> _Motel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMotel_IDChanging(int value);
    partial void OnMotel_IDChanged();
    partial void Onroom_IDChanging(int value);
    partial void Onroom_IDChanged();
    partial void OnElectricity_MeterChanging(System.Nullable<int> value);
    partial void OnElectricity_MeterChanged();
    partial void OnWater_MeterChanging(System.Nullable<int> value);
    partial void OnWater_MeterChanged();
    partial void OnElectricity_UsageChanging(System.Nullable<decimal> value);
    partial void OnElectricity_UsageChanged();
    partial void OnWater_UsageChanging(System.Nullable<decimal> value);
    partial void OnWater_UsageChanged();
    partial void OnRoom_StatusChanging(string value);
    partial void OnRoom_StatusChanged();
    partial void OnRoom_RentChanging(System.Nullable<decimal> value);
    partial void OnRoom_RentChanged();
    #endregion
		
		public room()
		{
			this._Room_Invoice = default(EntityRef<Room_Invoice>);
			this._Motel = default(EntityRef<Motel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motel_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Motel_ID
		{
			get
			{
				return this._Motel_ID;
			}
			set
			{
				if ((this._Motel_ID != value))
				{
					if (this._Motel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMotel_IDChanging(value);
					this.SendPropertyChanging();
					this._Motel_ID = value;
					this.SendPropertyChanged("Motel_ID");
					this.OnMotel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int room_ID
		{
			get
			{
				return this._room_ID;
			}
			set
			{
				if ((this._room_ID != value))
				{
					this.Onroom_IDChanging(value);
					this.SendPropertyChanging();
					this._room_ID = value;
					this.SendPropertyChanged("room_ID");
					this.Onroom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Meter", DbType="Int")]
		public System.Nullable<int> Electricity_Meter
		{
			get
			{
				return this._Electricity_Meter;
			}
			set
			{
				if ((this._Electricity_Meter != value))
				{
					this.OnElectricity_MeterChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Meter = value;
					this.SendPropertyChanged("Electricity_Meter");
					this.OnElectricity_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Meter", DbType="Int")]
		public System.Nullable<int> Water_Meter
		{
			get
			{
				return this._Water_Meter;
			}
			set
			{
				if ((this._Water_Meter != value))
				{
					this.OnWater_MeterChanging(value);
					this.SendPropertyChanging();
					this._Water_Meter = value;
					this.SendPropertyChanged("Water_Meter");
					this.OnWater_MeterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Electricity_Usage", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Electricity_Usage
		{
			get
			{
				return this._Electricity_Usage;
			}
			set
			{
				if ((this._Electricity_Usage != value))
				{
					this.OnElectricity_UsageChanging(value);
					this.SendPropertyChanging();
					this._Electricity_Usage = value;
					this.SendPropertyChanged("Electricity_Usage");
					this.OnElectricity_UsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Water_Usage", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Water_Usage
		{
			get
			{
				return this._Water_Usage;
			}
			set
			{
				if ((this._Water_Usage != value))
				{
					this.OnWater_UsageChanging(value);
					this.SendPropertyChanging();
					this._Water_Usage = value;
					this.SendPropertyChanged("Water_Usage");
					this.OnWater_UsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Status", DbType="VarChar(255)")]
		public string Room_Status
		{
			get
			{
				return this._Room_Status;
			}
			set
			{
				if ((this._Room_Status != value))
				{
					this.OnRoom_StatusChanging(value);
					this.SendPropertyChanging();
					this._Room_Status = value;
					this.SendPropertyChanged("Room_Status");
					this.OnRoom_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Rent", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Room_Rent
		{
			get
			{
				return this._Room_Rent;
			}
			set
			{
				if ((this._Room_Rent != value))
				{
					this.OnRoom_RentChanging(value);
					this.SendPropertyChanging();
					this._Room_Rent = value;
					this.SendPropertyChanged("Room_Rent");
					this.OnRoom_RentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="room_Room_Invoice", Storage="_Room_Invoice", ThisKey="Motel_ID,room_ID", OtherKey="Motel_ID,room_ID", IsUnique=true, IsForeignKey=false)]
		public Room_Invoice Room_Invoice
		{
			get
			{
				return this._Room_Invoice.Entity;
			}
			set
			{
				Room_Invoice previousValue = this._Room_Invoice.Entity;
				if (((previousValue != value) 
							|| (this._Room_Invoice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Room_Invoice.Entity = null;
						previousValue.room = null;
					}
					this._Room_Invoice.Entity = value;
					if ((value != null))
					{
						value.room = this;
					}
					this.SendPropertyChanged("Room_Invoice");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_room", Storage="_Motel", ThisKey="Motel_ID", OtherKey="Motel_ID", IsForeignKey=true)]
		public Motel Motel
		{
			get
			{
				return this._Motel.Entity;
			}
			set
			{
				Motel previousValue = this._Motel.Entity;
				if (((previousValue != value) 
							|| (this._Motel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motel.Entity = null;
						previousValue.rooms.Remove(this);
					}
					this._Motel.Entity = value;
					if ((value != null))
					{
						value.rooms.Add(this);
						this._Motel_ID = value.Motel_ID;
					}
					else
					{
						this._Motel_ID = default(int);
					}
					this.SendPropertyChanged("Motel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserProfile")]
	public partial class UserProfile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_user;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private System.Nullable<int> _MotelID;
		
		private string _Phone_Number;
		
		private string _Email;
		
		private string _userrole;
		
		private EntitySet<img> _imgs;
		
		private EntitySet<Motel> _Motels;
		
		private EntitySet<Video> _Videos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_userChanging(int value);
    partial void OnID_userChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnMotelIDChanging(System.Nullable<int> value);
    partial void OnMotelIDChanged();
    partial void OnPhone_NumberChanging(string value);
    partial void OnPhone_NumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnuserroleChanging(string value);
    partial void OnuserroleChanged();
    #endregion
		
		public UserProfile()
		{
			this._imgs = new EntitySet<img>(new Action<img>(this.attach_imgs), new Action<img>(this.detach_imgs));
			this._Motels = new EntitySet<Motel>(new Action<Motel>(this.attach_Motels), new Action<Motel>(this.detach_Motels));
			this._Videos = new EntitySet<Video>(new Action<Video>(this.attach_Videos), new Action<Video>(this.detach_Videos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(255)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="VarChar(255)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotelID", DbType="Int")]
		public System.Nullable<int> MotelID
		{
			get
			{
				return this._MotelID;
			}
			set
			{
				if ((this._MotelID != value))
				{
					this.OnMotelIDChanging(value);
					this.SendPropertyChanging();
					this._MotelID = value;
					this.SendPropertyChanged("MotelID");
					this.OnMotelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_Number", DbType="Char(11)")]
		public string Phone_Number
		{
			get
			{
				return this._Phone_Number;
			}
			set
			{
				if ((this._Phone_Number != value))
				{
					this.OnPhone_NumberChanging(value);
					this.SendPropertyChanging();
					this._Phone_Number = value;
					this.SendPropertyChanged("Phone_Number");
					this.OnPhone_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userrole", DbType="VarChar(255)")]
		public string userrole
		{
			get
			{
				return this._userrole;
			}
			set
			{
				if ((this._userrole != value))
				{
					this.OnuserroleChanging(value);
					this.SendPropertyChanging();
					this._userrole = value;
					this.SendPropertyChanged("userrole");
					this.OnuserroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserProfile_img", Storage="_imgs", ThisKey="ID_user", OtherKey="ID_user")]
		public EntitySet<img> imgs
		{
			get
			{
				return this._imgs;
			}
			set
			{
				this._imgs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserProfile_Motel", Storage="_Motels", ThisKey="ID_user", OtherKey="ID_user")]
		public EntitySet<Motel> Motels
		{
			get
			{
				return this._Motels;
			}
			set
			{
				this._Motels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserProfile_Video", Storage="_Videos", ThisKey="ID_user", OtherKey="ID_user")]
		public EntitySet<Video> Videos
		{
			get
			{
				return this._Videos;
			}
			set
			{
				this._Videos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_imgs(img entity)
		{
			this.SendPropertyChanging();
			entity.UserProfile = this;
		}
		
		private void detach_imgs(img entity)
		{
			this.SendPropertyChanging();
			entity.UserProfile = null;
		}
		
		private void attach_Motels(Motel entity)
		{
			this.SendPropertyChanging();
			entity.UserProfile = this;
		}
		
		private void detach_Motels(Motel entity)
		{
			this.SendPropertyChanging();
			entity.UserProfile = null;
		}
		
		private void attach_Videos(Video entity)
		{
			this.SendPropertyChanging();
			entity.UserProfile = this;
		}
		
		private void detach_Videos(Video entity)
		{
			this.SendPropertyChanging();
			entity.UserProfile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Video")]
	public partial class Video : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _video_ID;
		
		private System.Nullable<int> _ID_user;
		
		private System.Nullable<System.DateTime> _updatedAt;
		
		private System.Nullable<System.DateTime> _createdAt;
		
		private string _Link;
		
		private EntityRef<UserProfile> _UserProfile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvideo_IDChanging(int value);
    partial void Onvideo_IDChanged();
    partial void OnID_userChanging(System.Nullable<int> value);
    partial void OnID_userChanged();
    partial void OnupdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedAtChanged();
    partial void OncreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedAtChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public Video()
		{
			this._UserProfile = default(EntityRef<UserProfile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_video_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int video_ID
		{
			get
			{
				return this._video_ID;
			}
			set
			{
				if ((this._video_ID != value))
				{
					this.Onvideo_IDChanging(value);
					this.SendPropertyChanging();
					this._video_ID = value;
					this.SendPropertyChanged("video_ID");
					this.Onvideo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int")]
		public System.Nullable<int> ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					if (this._UserProfile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedAt", DbType="Date")]
		public System.Nullable<System.DateTime> updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this.OnupdatedAtChanging(value);
					this.SendPropertyChanging();
					this._updatedAt = value;
					this.SendPropertyChanged("updatedAt");
					this.OnupdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="Date")]
		public System.Nullable<System.DateTime> createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(255)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserProfile_Video", Storage="_UserProfile", ThisKey="ID_user", OtherKey="ID_user", IsForeignKey=true)]
		public UserProfile UserProfile
		{
			get
			{
				return this._UserProfile.Entity;
			}
			set
			{
				UserProfile previousValue = this._UserProfile.Entity;
				if (((previousValue != value) 
							|| (this._UserProfile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserProfile.Entity = null;
						previousValue.Videos.Remove(this);
					}
					this._UserProfile.Entity = value;
					if ((value != null))
					{
						value.Videos.Add(this);
						this._ID_user = value.ID_user;
					}
					else
					{
						this._ID_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("UserProfile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
