//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2home.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motel()
        {
            this.Rooms = new HashSet<Rooms>();
        }
    
        public int motel_id { get; set; }
        public int user_id { get; set; }
        public string motel_name { get; set; }
        public Nullable<int> number { get; set; }
        public string location { get; set; }
        public Nullable<decimal> price { get; set; }
        public string is_available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}
