//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2home.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int room_id { get; set; }
        public string room_type { get; set; }
        public int rent { get; set; }
        public Nullable<int> is_rent_pay { get; set; }
        public string is_available { get; set; }
        public Nullable<int> motel_id { get; set; }
    
        public virtual Motel Motel { get; set; }
    }
}
